Colors:
  FF: "fad390" #Flat Flesh
  SQ: "f6b93b" #Squash Blossom
  IP: "fa983a" #Iceland Poppy
  CO: "e58e26" #Carrot Orange
  MM: "f8c291" #Melon Melody
  MR: "e55039" #Mandarin Red
  TR: "eb2f06" #Tomato Red
  JR: "b71540" #Jalapeno Red
  LI: "6a89cc" #Livid
  AB: "4a69bd" #Azraq Blue
  YG: "1e3799" #Yue Guang Lan Blue
  DS: "0c2461" #Dark Sapphire
  SP: "82ccdd" #Spray
  DU: "60a3bc" #Dupain
  GS: "3c6382" #Good Samaritan
  FB: "0a3d62" #Forest Blues
  PG: "b8e994" #Paradise Green
  AG: "78e08f" #Aurora Green
  WA: "38ada9" #Waterfall
  RE: "079992" #Reef Encounter

Blacklist:
  NAME_TAG: "false"
  DIAMOND_SWORD: "false"