name: Earth
version: ${project.version}
main: com.github.polarbehrz.earth.Earth
api-version: 1.16
depend: [Vault]
softdepend: [PlaceholderAPI]

commands:
  rules:
    description: "RULES!!"
  map:
    description: "dyyyyyynnmap"
    aliases: [dynmap]
  store:
    description: "store"
  help:
    description: "awww creeper"
  wiki:
    description: "wikipedia"
  vip:
    description: "viip"
  vip+:
    description: "viip x2"
    aliases: [vipplus]
  mvp:
    description: "hypixel"
  mvp+:
    description: "hypixel v2"
    aliases: [mvpplus]
  nightvision:
    description: "nvm"
    aliases: [nv]
  alt:
    description: "Lists possible alt accounts of player."
    permission: altdetector.alt
  suffix:
    description: "toog"
    permission: xylum.suffix.use
  prefix:
    description: "pre"
    permission: xylum.prefix.use

permissions:
  nightvision.player:
    description: "Toggle the night vision of another player."
    default: op
  nightvision.use:
    description: "Enables use of /nv."
    default: false
  xylum.anvil.use:
    description: "Use colored anvils"
    default: true
  altdetector.alt:
    description: Allows use of the /alt command
    default: op
  altdetector.exempt:
    description: Exempts player from data being saved and a lookup being done when joining the server
    default: false
  altdetector.notify:
    description: Notifies this player when an alt is detected
    default: op
  motd.perks:
    default: false
  motd.vip:
    default: false
  motd.vip+:
    default: false
  motd.mvp:
    default: false
  motd.mvp+:
    default: false
